name: ✨ Feature Request
description: Suggest a new feature for Guardian-AA
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details about your idea.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - ZK Proof System (prover/)
        - Smart Contracts (contracts/)
        - SDK (sdk/)
        - Mobile App (mobile/)
        - AI Assistant
        - Documentation (docs/)
        - DevOps/Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Important for core functionality
        - Critical - Blocking major use case
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas would this feature impact? (Select all that apply)
      options:
        - label: Security
        - label: Performance
        - label: User Experience
        - label: Developer Experience
        - label: Privacy
        - label: Scalability
        - label: Gas Optimization
        - label: Cross-chain Compatibility

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share
      placeholder: |
        Any thoughts on implementation approach, technical considerations, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: |
        Screenshots, diagrams, links to similar features in other projects, etc. 